我来捣乱了
BingyanStudio/BingyanDevKit pull request #17
Opened 2024-10-29 09:40 UTC by GalliumNitride-DL

PropertyDrawer真好玩！虽然可能写了一坨 * 吧

### Feat

A `PropertyDrawer` that gives users the option to modify inspector `Vector3` fields by dragging a position handle in the scene view.

![image](https://github.com/user-attachments/assets/1c677536-1b15-4a74-8dec-ff6b12c3a0ef)

Fairly simple to use
![image](https://github.com/user-attachments/assets/4b522cc8-32ab-4e22-b033-efec3f26c680)

### Problems

- Code sucks
- Might introduce overhead
- `Vector3` field overlaps with buttons when the Inspector window is too narrow
- Didn't strictly follow formatting guidelines
- Not user-friendly ~~at all~~

### By the way

This is my first PR to a public repo! ~~Please don't tell me that Unity already made these with everything so much better and I just wasted two days on this~~

2024-10-29 09:41 UTC, jyi2ya commented
哇，是野生的神秘 game dev

你好呀！

2024-10-29 09:43 UTC, GalliumNitride-DL commented
> 哇，是野生的神秘 game dev
> 
> 你好呀！

自己人，冰岩新的小东西🤔

2024-10-29 09:47 UTC, jyi2ya commented
坏耶，那你怎么没在 github.com/BingyanStudio 里

组长该干活辣！

________________________________________
From: GaN ***@***.***>
Sent: Tuesday, October 29, 2024 5:43 PM
To: BingyanStudio/BingyanDevKit
Cc: jyi2ya; Comment
Subject: Re: [BingyanStudio/BingyanDevKit] 我来捣乱了 (PR #17)

哇，是野生的神秘 game dev

你好呀！

自己人，冰岩新的小东西🤔

—
Reply to this email directly, view it on GitHub<https://github.com/BingyanStudio/BingyanDevKit/pull/17#issuecomment-2443722499>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AUWKWUJ3RAR5OTCSSBXFWOLZ55KEJAVCNFSM6AAAAABQZNFLT2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDINBTG4ZDENBZHE>.
You are receiving this because you commented.Message ID: ***@***.***>

2024-10-29 12:37 UTC, Hamster5295 requested changes
不需要引入新的命名空间：    
* Runtime 归入 Bingyan 空间，
* Editor 文件夹下归入 Bingyan.Editor 空间即可

2024-10-29 12:47 UTC, Hamster5295 reviewed
命名风格可以改进：
1. `EasyLocation`:   
这个名称没有直接反映它的功能，可能会引起疑惑。  
可以考虑使用 `PositionEdit` 或类似名称  


2. `Vector3Drawer`:  
这个名称过于泛化了，所有对 `Vector3` 属性进行绘制的 `PropertyDrawer` 均可以被称为此名字。  
可以考虑使用 `PositionEditDrawer` 或类似名称。注意与 `EasyLocation` 重命名后的名称一致。

2024-10-30 02:19 UTC, GalliumNitride-DL commented
### Renamed to

- `Editor/PropertyEditor/EasyPositionEdit/EasyPositionEditDrawer.cs`
- `Editor/PropertyEditor/EasyPositionEdit/EasyPositionEditSceneMonitor.cs`
- `Runtime/Attribute/EasyPositionEditAttribute.cs`

2024-10-30 05:17 UTC, Hamster5295 approved these changes

2024-10-30 05:19 UTC, merged

2024-10-30 05:20 UTC, Hamster5295 commented
已经合并  
另外，你已经被拉进组织了，之后直接在 dev 分支 push 即可